import type { Metadata } from "next";
import { clinic } from "./clinic-data";

type PageMetaInput = {
  title: string;
  description: string;
  path: string;
  type?: "website" | "article";
};

/** The share image generated by app/opengraph-image.tsx. */
const shareImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${clinic.name} — dentist in Thaltej, Ahmedabad`,
};

/**
 * Per-page metadata with a matching canonical, Open Graph and Twitter card.
 * A page-level `openGraph` object replaces the root one, so the share image is set explicitly.
 */
export function pageMetadata({ title, description, path, type = "website" }: PageMetaInput): Metadata {
  const fullTitle = `${title} | ${clinic.name}`;
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      locale: "en_IN",
      siteName: clinic.name,
      url: path,
      title: fullTitle,
      description,
      images: [shareImage],
    },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [shareImage.url] },
  };
}
